import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'

// Deterministic reference data only. Never seed workouts or measured body weights.
const catalog = JSON.parse(
  readFileSync(new URL('../src/fitness/catalog.json', import.meta.url), 'utf8')
)
const quote = (value) =>
  value == null
    ? 'NULL'
    : typeof value === 'number'
      ? String(value)
      : `'${String(value).replaceAll("'", "''")}'`
const statements = [
  '-- Generated by npm run fitness:seed:generate. Re-runnable; preserves personal data and plan changes.',
  'INSERT OR IGNORE INTO fitness_profile(id) VALUES(1);',
  "INSERT OR IGNORE INTO fitness_workout_plan(id,name,version) VALUES('personal-v1','Personal Training Plan V1',1);"
]
for (const exercise of catalog) {
  statements.push(
    `INSERT INTO fitness_exercise(id,data) VALUES(${quote(exercise.id)},${quote(JSON.stringify(exercise))}) ON CONFLICT(id) DO UPDATE SET data=excluded.data;`
  )
}
const days = [
  [
    'A',
    '胸 + 肩 + 核心',
    '胸 · 肩 · 核心',
    [
      ['barbell-bench-press', 3, 6, 10],
      ['incline-dumbbell-press', 3, 8, 12],
      ['dumbbell-shoulder-press', 3, 8, 12],
      ['lateral-raise', 3, 12, 20],
      ['face-pull', 2, 12, 20],
      ['crunch', 3, 10, 15]
    ]
  ],
  [
    'B',
    '腿 + 臀 + 核心',
    '腿 · 臀 · 核心',
    [
      ['squat', 3, 6, 10],
      ['romanian-deadlift', 3, 8, 12],
      ['bulgarian-split-squat', 2, 8, 12, null, 0, '每腿'],
      ['leg-curl', 2, 10, 15],
      ['calf-raise', 2, 12, 20],
      ['hanging-leg-raise', 3, 8, 15]
    ]
  ],
  [
    'C',
    '背 + 体态 + 手臂',
    '背 · 体态 · 手臂',
    [
      ['pull-up', 3, 0, 0, null, 0, '按实际次数记录，保留余力'],
      ['lat-pulldown', 3, 8, 12],
      ['seated-row', 3, 8, 12],
      ['reverse-fly', 3, 12, 20],
      ['biceps-curl', 2, 10, 15],
      ['pallof-press', 3, 0, 0, null, 0, '2–3 组，按实际次数记录']
    ]
  ],
  [
    'D',
    '全身 + 胸肩加强',
    '全身 · 胸 · 肩',
    [
      ['incline-dumbbell-press', 3, 8, 12],
      ['goblet-squat', 3, 8, 12],
      ['single-arm-row', 3, 8, 12, null, 0, '每侧'],
      ['lateral-raise', 3, 12, 20],
      ['push-up', 2, 0, 0, null, 0, '按实际次数记录，保留余力'],
      ['incline-walk', 1, 0, 0, 900, 1, '可选 10–15 分钟']
    ]
  ]
]
for (const [position, [id, name, focus, entries]] of days.entries()) {
  statements.push(
    `INSERT OR IGNORE INTO fitness_workout_day(id,planId,name,position,focus) VALUES(${quote(id)},'personal-v1',${quote(name)},${position},${quote(focus)});`
  )
  for (const [
    index,
    [exercise, sets, min, max, duration = null, optional = 0, note = '']
  ] of entries.entries()) {
    if (!catalog.some((e) => e.id === exercise)) throw new Error(`Missing exercise: ${exercise}`)
    statements.push(
      `INSERT OR IGNORE INTO fitness_workout_exercise(id,dayId,exerciseId,position,sets,repsMin,repsMax,durationSeconds,optional,note) VALUES(${[`${id}-${index + 1}`, id, exercise, index, sets, min, max, duration, optional, note].map(quote).join(',')});`
    )
  }
}
for (const [id, name, description] of [
  ['first-workout', '开始，就是进步', '完成第一次训练'],
  ['twelve-workouts', '持续投入', '累计完成 12 次训练'],
  ['fifty-workouts', '长期主义', '累计完成 50 次训练'],
  ['four-weeks', '找到节奏', '连续 4 周达到每周 3 次训练目标'],
  ['ten-pull-ups', '向上十次', '在已完成训练中，单组完成 10 次标准引体向上']
])
  statements.push(
    `INSERT OR IGNORE INTO fitness_achievement(id,name,description) VALUES(${[id, name, description].map(quote).join(',')});`
  )
mkdirSync(new URL('../seeds/', import.meta.url), { recursive: true })
writeFileSync(new URL('../seeds/fitness.sql', import.meta.url), statements.join('\n') + '\n')
console.log(
  `Generated ${catalog.length} exercises, 4 days, 24 plan entries, 5 achievements. No training records.`
)
